language: scala
script:
  - sbt clean +test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      sh "$TRAVIS_BUILD_DIR/.travis.prepare.bintray.sh" &&
      sbt 'set version := version.value.replace("-SNAPSHOT", "." + System.getenv("TRAVIS_BUILD_NUMBER"))' +publish
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      bash .publishWeb.sh



notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/36f3020f807b8e0e0480
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

